apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hakibets-ui.fullname" . }}
  labels:
    {{- include "hakibets-ui.labels" . | nindent 4 }}
data:
    {{- range $key, $value := .Values.properties }}
    {{ $key | replace "." "_" | replace "-" "" | upper }}: {{ $value | quote}}
    {{- end }}
